name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20 # Or your preferred Node.js version
          cache: 'yarn' # Caching dependencies

      - name: Install dependencies
        run: yarn install

      - name: Build with esbuild
        run: yarn build

      - name: List build artifacts for google-phonelib-js
        run: ls -R packages/google-phonelib-js/dist

      - name: List build artifacts for arctics-google-phonelib
        run: ls -R packages/arctics-google-phonelib/dist

      - name: Check NPM_TOKEN
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is not set"
            exit 1
          else
            echo "NPM_TOKEN is set"
          fi

      - name: Configure npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Verify package name (arctics-google-phonelib)
        run: |
          PACKAGE_NAME=$(jq -r '.name' packages/arctics-google-phonelib/package.json)
          echo "Package Name: $PACKAGE_NAME" # For debugging
          if [ "$PACKAGE_NAME" != "@arctics/google-phonelib" ]; then # Replace with your actual package name
            echo "Package name is incorrect: $PACKAGE_NAME"
            exit 1
          else
            echo "Package name is correct: $PACKAGE_NAME"
          fi

      - name: Publish to npm
        run: |
          cd packages/arctics-google-phonelib
          echo "Current directory: $(pwd)"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
