name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Or your preferred Node.js version
          cache: 'yarn' # Caching dependencies

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build with esbuild
        run: yarn build

      - name: Check NPM_TOKEN
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is not set"
            exit 1
          else
            echo "NPM_TOKEN is set"
          fi

      - name: Verify package name (arctics-google-phonelib)
        run: |
          PACKAGE_NAME=$(jq -r '.name' packages/arctics-google-phonelib/package.json)
          echo "Package Name: $PACKAGE_NAME" # For debugging
          if [ "$PACKAGE_NAME" != "@arctics/google-phonelib" ]; then # Replace with your actual package name
            echo "Package name is incorrect: $PACKAGE_NAME"
            exit 1
          else
            echo "Package name is correct: $PACKAGE_NAME"
          fi

      - name: Publish to npm
        run: |
          cd packages/arctics-google-phonelib
          echo "Current directory: $(pwd)"  # Important: Confirm directory
          npm whoami
          npm publish --access public # Or --dry-run first
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
